### ISSUE TITLE
New version PS Remote Play.

### ISSUE THREAD

**Issue by dimonkin86** [starshinata/PS4-Keyboard-and-Mouse-Adapter#19] opened 2020-10-14 10:51 UTC
New version PS Remote Play, and app error: "PS4 Remote play is required".
or how i can start app "PS4KeyboardAndMouseAdapter" without checking version of PS Remote Play? (ohhh, if i open app, then see error "ps4 remote required", and quickly open the new app "PS Remote play", all works (if i press O button, PS4RemotePlay try to connect PS4) , but now i can't connect to my ps4... work on it.)

and wishlist :-) ability to stop M/KB from working on RemotePlay so user can use computer as normal without messing up the PS4, or add this function on top big button (with mouse func). Big thx for app!!!

**Comment by tamammama** [comment] 2020-10-14 13:51
hi how are u doing with this proplem ? 
i have the same and i cant open it 
plese if you find any thing usefull tell me

**Comment by dimonkin86** [comment] 2020-10-15 06:04
> hi how are u doing with this proplem ?
> i have the same and i cant open it
> plese if you find any thing usefull tell me

try quickly open PS Remote Play, after you close error "PS4 Remote play is required", after that "PS4KeyboardAndMouseAdapter"  will open and work fine. But now i can't connect to my ps4 on new app PS Remote Play, work on it.

**Comment by SeifBrg** [comment] 2020-10-15 10:14
> > hi how are u doing with this proplem ?
> > i have the same and i cant open it
> > plese if you find any thing usefull tell me
> 
> try quickly open PS Remote Play, after you close error "PS4 Remote play is required", after that "PS4KeyboardAndMouseAdapter" will open and work fine (if i click O button, ps remote play trying connect to ps4). But now i can't connect to my ps4 on new app PS Remote Play, work on it.
> ![snap](https://user-images.githubusercontent.com/72864217/96083358-14cd9000-0ece-11eb-9116-b81b2c470b73.JPG)

You need to update your ps4 system software!

**Comment by abhishekrana26** [comment] 2020-10-15 10:31
HI superb application. was working fine till yesterday. but as soon as i updated ps4 remote play to PS remote play. IT stopped working.
@dimonkin86 : unable to get the application started by your Quick open tecnique.

Pls guys.

**Comment by abhishekrana26** [comment] 2020-10-15 10:35
> > > hi how are u doing with this proplem ?
> > > i have the same and i cant open it
> > > plese if you find any thing usefull tell me
> > 
> > 
> > try quickly open PS Remote Play, after you close error "PS4 Remote play is required", after that "PS4KeyboardAndMouseAdapter" will open and work fine (if i click O button, ps remote play trying connect to ps4). But now i can't connect to my ps4 on new app PS Remote Play, work on it.
> > ![snap](https://user-images.githubusercontent.com/72864217/96083358-14cd9000-0ece-11eb-9116-b81b2c470b73.JPG)
> 
> You need to update your ps4 system software!

I updated my PS4 system software ,, but cant open the  PS4KeyboardAndMouseAdapter at all
![image](https://user-images.githubusercontent.com/72919392/96112358-1ca62800-0f00-11eb-8b0f-fa7d7a857275.png)

**Comment by SeifBrg** [comment] 2020-10-15 10:44
> HI superb application. was working fine till yesterday. but as soon as i updated ps4 remote play to PS remote play. IT stopped working.
> @dimonkin86 : unable to get the application started by your Quick open tecnique.
> 
> Pls guys.

Me too :(

**Comment by dimonkin86** [comment] 2020-10-15 11:50
> You need to update your ps4 system software!

WOW, i play from work, and don't know about SU ))))))) thx man.

about Quick open technique i add snap, click close on Error, than quick open ps remote play app (and don't forget close Update app)... if u want i can add more snap.

**Comment by dimonkin86** [comment] 2020-10-15 12:30
all work! 
![snap](https://user-images.githubusercontent.com/72864217/96123323-b7eccc80-0f03-11eb-8ae3-d12bb0a2e2bf.JPG)

**Comment by SeifBrg** [comment] 2020-10-15 16:54
> all work!
> ![snap](https://user-images.githubusercontent.com/72864217/96123323-b7eccc80-0f03-11eb-8ae3-d12bb0a2e2bf.JPG)




> > You need to update your ps4 system software!
> 
> WOW, i play from work, and don't know about SU ))))))) thx man.
> 
> about Quick open technique i add snap, click close on Error, than quick open ps remote play app (and don't forget close Update app)... if u want i can add more snap. Trying make video/gif.

Thaaaank youu so much!!I understood your technique and it works for me! :D

**Comment by abhishekrana26** [comment] 2020-10-15 17:21
> > You need to update your ps4 system software!
> 
> WOW, i play from work, and don't know about SU ))))))) thx man.
> 
> about Quick open technique i add snap, click close on Error, than quick open ps remote play app (and don't forget close Update app)... if u want i can add more snap. Trying make video/gif.

hey dint get it i guess i m doing something wrong can you make a small video

**Comment by abhishekrana26** [comment] 2020-10-15 21:29
as soon as i click the close on error and opens PS remote play, the PS4KeyboardAndMouseAdapter CLOSES. AND ONLY PS Remote pLAY OPENS UP. 
:((, NEED YOUR HELP GUYS

**Comment by dimonkin86** [comment] 2020-10-16 05:17
1. Open "PS4KeyboardAndMouseAdapter", close error "PS4 Remote play is required".
2.  than quick open ps remote play app.
3. close Update app click "Cancel".
4. wait, all app will start and work together.

and i add gif, see it.
![bandicam 2020-10-16 09-01-31-747](https://user-images.githubusercontent.com/72864217/96216036-70f8e880-0f90-11eb-919d-1361cce8c0b0.jpg)
![bandicam 2020-10-16 09-01-41-559](https://user-images.githubusercontent.com/72864217/96216037-722a1580-0f90-11eb-9c68-47fd2584c04e.jpg)
![bandicam 2020-10-16 09-01-49-542](https://user-images.githubusercontent.com/72864217/96216038-722a1580-0f90-11eb-9565-dd86bb63b9d0.jpg)
![bandicam 2020-10-16 09-02-01-745](https://user-images.githubusercontent.com/72864217/96216041-72c2ac00-0f90-11eb-9e64-a3ca406d4ac3.jpg)
![bandicam-2020-10-16-09-11-22-135](https://user-images.githubusercontent.com/72864217/96216055-76eec980-0f90-11eb-8208-d866bb7fe990.gif)

**Comment by abhishekrana26** [comment] 2020-10-16 13:16
okay the problem is after step 2 my PS remote play is going to step 4 .
no step 3 (update window) for me.

**Comment by dimonkin86** [comment] 2020-10-16 13:30
> okay the problem is after step 2 my PS remote play is going to step 4 .
> no step 3 (update window) for me.

can u only do 1 step, and wait error PS4 Remote play is required - than click ok button, and wait update install.?

**Comment by abhishekrana26** [comment] 2020-10-16 14:38
> > okay the problem is after step 2 my PS remote play is going to step 4 .
> > no step 3 (update window) for me.
> 
> can u only do 1 step, and wait error PS4 Remote play is required - than click ok button, and wait update install.?

after pressing OkAY, NOTHING Happens :((

**Comment by abhishekrana26** [comment] 2020-10-16 14:42
HEYYY SUPPERR IT WORKED 
REINSTALLED REMOTE PLAY AND TURN OFF FIREWALL thanks guysss
njoy 👍

**Comment by pancakeslp** [comment] 2020-10-18 23:04
Its a two line change in the code to fix this
I've raised a PR for it at https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/pull/21

In the mean time, I have done a build locally of the changes and attached it here (sorry no fancy installer)
If you dont trust it dont download it
[PS4KeyboardAndMouseAdapter-bundle.tar.gz](https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/files/5398332/PS4KeyboardAndMouseAdapter-bundle.tar.gz)

**Comment by tamammama** [comment] 2020-10-19 00:10
Thx

في الاثنين، ١٩ أكتوبر، ٢٠٢٠ ١:٠٤ ص pancakeslp <notifications@github.com>
كتب:

**Comment by tamammama** [comment] 2020-10-19 00:11
Appreciate it

في الاثنين، ١٩ أكتوبر، ٢٠٢٠ ٢:١٠ ص tama sama <tama900005@gmail.com> كتب:

**Comment by ahmedkashif69** [comment] 2020-10-20 09:33
Guys It works Thanksssss to the guy who made the snaps

**Comment by keeganostrowski** [comment] 2020-10-20 21:03
(Recommented this from the thread I started)

So I'm not sure if this fix only worked for me, but hopefully it works for you too.

Step 1: UNINSTALL your current PS Remote Play

Step 2: REINSTALL

Step 3: When reinstalling, make sure when it asks you 
"Install PS Remote Play to:
C:\Program Files (x86)\Sony\PS Remote Play"
That you change
"C:\Program Files (x86)\Sony\PS Remote Play"
To
"C:\Program Files (x86)\PS4 Remote Play"
(MUST REMOVE "\Sony" AND MUST ADD A "4" TO "PS")

![image](https://user-images.githubusercontent.com/73199067/96643260-29e65c80-12dc-11eb-8ff6-7cedd8b63bfa.png)

![image](https://user-images.githubusercontent.com/73199067/96643281-336fc480-12dc-11eb-9986-153b038a08e8.png)

![image](https://user-images.githubusercontent.com/73199067/96643299-38347880-12dc-11eb-8cb5-2c19f31053d7.png)

Step 4: Start PS4Keyboard&MouseAdapter

Step 5: Profit???

![image](https://user-images.githubusercontent.com/73199067/96643400-5bf7be80-12dc-11eb-9154-334082cd888c.png)

It was that simple for me.

Now I can play Bloodborne with my Guitar Hero controller on stream via PS Remote Play. 

@dimonkin86 
@SeifBrg 
@abhishekrana26

**Comment by starshinata** [comment] 2020-10-22 13:47
Hi all, sorry for neglecting this tool for the past 3 months, super busy at my job these days. Will release a new fix this weekend. I'm very happy that you guys found a hack to make it work! I made a discord server https://discord.gg/zH4b8p4 , feel free to join it so you guys can ask other members and help each other there in case I'm not online.

**Comment by pancakeslp** [comment] 2020-11-11 02:03
Closing issue as have released PS4-Keyboard-and-Mouse-Adapter v1.0.8 which with updated paths to new Sony Remote play client.
Please reopen if you are experiencing issue on v1.0.8

**Closed by pancakeslp** 2020-11-11 02:03 UTC
