### ISSUE TITLE
remove controller joystick feeling

### ISSUE THREAD

**Issue by cashl7** [starshinata/PS4-Keyboard-and-Mouse-Adapter#98] opened 2024-10-05 17:54 UTC
### Have you read the FAQ ?
* [x] I have read the FAQ which is available at https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/blob/master/documentation/frequently-asked-questions.md

### You are raising an Issue, what can you generalise it as ?
* [ ] Problem - something is wrong
* [ ] Enhancement suggestion - i have an idea to make something better
* [ y] Other

### What Console are you using
* [y ] PS5
* [ n] PS4

### What version of PS4KMA are you using ?
(Look at the title bar, if unsure send screenshot of PS4KMA app)

### What emulation method are you using ?
* [ ] ViGEm and NO process injection for bottom toolbar
* [ y] ViGEm and process injection for bottom toolbar *recommended*
* [ ] NO ViGEm and just process injection

### Describe your issue
it feels too like controller ik it is using a joystick but do u know anyway to make it feel like a mouse more like settings or sens changes

**Comment by pancakeslp** [comment] 2024-10-05 19:16
Duplicate of https://github.com/starshinata/PS4-Keyboard-and-Mouse-Adapter/issues/62

**Closed by pancakeslp** 2024-10-05 19:16 UTC
